version: '3.1'

services:
  db:
    image: postgres:12
    container_name: local-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=elisity
    volumes:
      - elisity-database-data:/var/lib/postgresql/data

volumes:
  elisity-database-data:
